### ISSUE TITLE
Tiago Ribeiro's suggestion

### ISSUE THREAD

**Issue by Harbs** [jonasmonnier/Multipart.as#3]
I was using Multipart to upload binary data with no issues. (ImageData with JPEG encoding)

I just added uploading some XML data which was reconstructed from XML data originally downloaded and when using Multipart to upload it I was getting a Security Sandbox Violation.

Changing the code to this fixed it:

			//r.contentType = "multipart/form-data; boundary=" + boundary;

			// Tiago Ribeiro's suggestion
			// Not necessary until proven otherwise
			r.requestHeaders.push(new URLRequestHeader("Content-type", "multipart/form-data; boundary=" + boundary));

Note: Adding the URLRequestHeader alone did not help. I needed to comment out the setting the contentType before the Security Sandbox Violation went away.

The takeaway is that it really depends on the content type as to whether the suggestion is necessary, but when it's necessary, the suggestion helps.

Harbs

**Comment by jonasmonnier** [comment]
Thank you harbs. I'll fix this.

**Comment by jonasmonnier** [comment]
Fixed
